### ISSUE TITLE
While cloning the repo stuck at 0.0%

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#78] opened 2017-01-25 11:14 UTC
May be caused by the public wifi which I'm using, I'll report if same happens with good internet connection.

**Comment by XyLoNaMiyX** [comment] 2017-01-25 11:43
Could you please provide the repository URL (or F-Droid application)?

**Comment by licaon-kter** [comment] 2017-01-25 12:12
Saw this once too, I guess it was related to #69 
Closing and reopening the app made it work.

**Comment by XyLoNaMiyX** [comment] 2017-01-25 12:15
> Saw this once too, I guess it was related to #69

That issue was already fixed when I released the `v0.9.7`, though. I know it can sometimes take long at 0%, but then it should work normally.

**Comment by OffifialMITX** [comment] 2017-01-25 13:32
I tried this with Stringlate itself and as I thought, the problem was the hotspot, works fine with my own wifi.

**Closed** 2017-01-25 13:35 UTC

**Comment by OffifialMITX** [comment] 2017-01-29 15:48
Now I'm stuck at 0.1% trying to download [Mysplash](https://github.com/WangDaYeeeeee/Mysplash) after a couple of minutes Stringlate says that no Strings were found.

I used my own Wi-Fi this time so that's not the problem.

**Comment by XyLoNaMiyX** [comment] 2017-01-29 15:51
> Now I'm stuck at 0.1% trying to download Mysplash

Very strange behaviour. I can reproduce the "bug", or whatever this is.

**Comment by XyLoNaMiyX** [comment] 2017-01-29 16:11
Now it gets stuck at 28%! But at least the progress shows the % of cloned objects, so although some objects may be very, *very* large (and I don't seem to be able to tell *how* large), the progress is now more accurate.

**Comment by XyLoNaMiyX** [comment] 2017-01-30 18:12
The problem if I added back the (faster) old way to download the strings for GitHub repositories *only*, then the image for the application you're trying to translated *wouldn't be* downloaded. And it would be awkward that this only happened for GitHub repositories. Any ideas?

**Comment by OffifialMITX** [comment] 2017-01-31 07:28
Maybe downloading the image from the F-Droid repo/the installed app itself, if avalible?

You also don't need the whole repo only for that image, I guess.

Am 30. Januar 2017 19:13:00 MEZ, schrieb Lonami <notifications@github.com>:
>The problem if I added back the (faster) old way to download the
>strings for GitHub repositories *only*, then the image for the
>application you're trying to translated *wouldn't be* downloaded. And
>it would be awkward that this only happened for GitHub repositories.
>Any ideas?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/78#issuecomment-276143229

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment] 2017-01-31 08:43
> Maybe downloading the image from the F-Droid repo/the installed app itself, if avalible?

Nope, impossible. The URL of the repository for a given application is not enough information to determine the package, which I need to retrieve the image. I would need to download something.

> You also don't need the whole repo only for that image

I know, neither I do to retrieve the strings. But `git clone` doesn't allow you to cherry pick files like "I only want `.xml` files".

**Comment by XyLoNaMiyX** [comment] 2017-02-01 12:23
As it turns out @OffifialMITX (I missed this), the repository has the strings under "_res/**resource**/values/strings.xml_" and not under "_res/values/strings.xml_" (note how there is no `/resuorce/` in between). I didn't even know this was possible, but it is. I added support for it on the [`7d02a59`](https://github.com/LonamiWebs/Stringlate/commit/7d02a59823a17e87d96f5fe4c9777045c81d9850) commit :)

Thanks for pointing this repository out.
