### ISSUE TITLE
Local export fails on Oreo

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#165] opened 2017-11-23 19:44 UTC
After upgrading to Android 8.0 Oreo, I noticed that all local export methods fail. Here's how: 

- Export to SD card - opens a file _picker_, can't see any folders or files in it 
- Share generated xml - crash 
- Copy to clipboard - crash 

The only way that seems to work is "Export repository" from main screen. 

Perhaps they need storage permission? Because from app info screen it seems Stringlate doesn't even want it.

**Comment by gsantner** [comment] 2017-11-23 23:06
Is this reproduceable in emulator too? Have no Oreo device yet

**Comment by Madis0** [comment] 2017-11-24 04:29
If it isn't an OxygenOS (OnePlus's skin) bug, it should be.

**Comment by Madis0** [comment] 2018-01-14 08:43
Can no longer reproduce the first two on a 8.1 AOSP-based ROM. It might have been an OOS bug.

**Comment by Lonami** [comment] 2018-01-14 08:48
Since nobody else complained about this, I'll close the issue and hope it works.

**Comment by Madis0** [comment] 2018-01-14 08:52
Copy to clipboard still crashes for me, maybe because of file size?

**Comment by Lonami** [comment] 2018-01-14 08:53
Can't guess, I would need to see a log. But it would be weird if it crashed due to file size.

**Comment by Madis0** [comment] 2018-01-14 08:56
```
01-14 10:33:12.754 I/ActivityManager(1286): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=io.github.lonamiwebs.stringlate cmp=io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity} from uid 1000
01-14 10:33:13.285 I/ActivityManager(1286): Start proc 26263:io.github.lonamiwebs.stringlate/u0a195 for activity io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity
01-14 10:33:15.830 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.DiscoverActivity} from uid 10195
01-14 10:36:00.630 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:41:21.016 E/AndroidRuntime(26263): Process: io.github.lonamiwebs.stringlate, PID: 26263
01-14 10:41:21.016 E/AndroidRuntime(26263): java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.writeReplaceStrings(ResourcesParser.java:584)
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.applyTemplate(ResourcesParser.java:646)
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.applyTemplate(RepoHandler.java:428)
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.mergeDefaultTemplate(RepoHandler.java:441)
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.exportToCopy(TranslateActivity.java:685)
01-14 10:41:21.016 E/AndroidRuntime(26263): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.onOptionsItemSelected(TranslateActivity.java:321)
01-14 10:41:21.019 W/ActivityManager(1286):   Force finishing activity io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity
01-14 10:41:21.038 I/ActivityManager(1286): Showing crash dialog for package io.github.lonamiwebs.stringlate u0
01-14 10:41:21.524 W/ActivityManager(1286): Activity pause timeout for ActivityRecord{6ee093f u0 io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity t1572 f}
01-14 10:41:22.684 I/ActivityManager(1286): Killing 26263:io.github.lonamiwebs.stringlate/u0a195 (adj 0): crash
01-14 10:41:22.738 I/WindowManager(1286): WIN DEATH: Window{c9b82f8 u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity}
01-14 10:41:22.741 I/WindowManager(1286): WIN DEATH: Window{7766c56 u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity}
01-14 10:41:22.747 I/ActivityManager(1286): Start proc 27502:io.github.lonamiwebs.stringlate/u0a195 for activity io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity
01-14 10:41:24.143 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:44:03.881 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:44:24.966 I/chatty  (27502): uid=10195(io.github.lonamiwebs.stringlate) identical 24 lines
01-14 10:44:35.608 I/chatty  (27502): uid=10195(io.github.lonamiwebs.stringlate) identical 22 lines
01-14 10:44:46.053 I/chatty  (27502): uid=10195(io.github.lonamiwebs.stringlate) identical 15 lines
01-14 10:46:15.503 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.SettingsActivity} from uid 10195
01-14 10:46:17.431 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.BrowserActivity (has extras)} from uid 10195
01-14 10:46:17.589 W/webs.stringlate(27502): type=1400 audit(0.0:361): avc: denied { read } for name="vmstat" dev="proc" ino=4026532129 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
01-14 10:46:17.590 I/ActivityManager(1286): Start proc 28420:com.android.webview:sandboxed_process0/u0i833 for webview_service io.github.lonamiwebs.stringlate/org.chromium.content.app.SandboxedProcessService0
01-14 10:46:17.609 W/cr_CrashFileManager(27502): /data/user/0/io.github.lonamiwebs.stringlate/cache/WebView/Crash Reports does not exist or is not a directory
01-14 10:46:21.931 I/ActivityManager(1286): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:io.github.lonamiwebs.stringlate cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10031
01-14 10:46:22.198 V/BatteryUtils(15300): package: io.github.lonamiwebs.stringlate
01-14 10:50:48.985 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:50:52.582 I/zygote64(27502): Deoptimizing io.github.lonamiwebs.stringlate.classes.resources.tags.ResTag io.github.lonamiwebs.stringlate.classes.resources.Resources.getTag(java.lang.String) due to JIT inline cache
01-14 10:51:45.086 E/AndroidRuntime(27502): Process: io.github.lonamiwebs.stringlate, PID: 27502
01-14 10:51:45.086 E/AndroidRuntime(27502): java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.writeReplaceStrings(ResourcesParser.java:584)
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.applyTemplate(ResourcesParser.java:646)
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.applyTemplate(RepoHandler.java:428)
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.mergeDefaultTemplate(RepoHandler.java:441)
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.exportToCopy(TranslateActivity.java:685)
01-14 10:51:45.086 E/AndroidRuntime(27502): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.onOptionsItemSelected(TranslateActivity.java:321)
01-14 10:51:45.092 W/ActivityManager(1286):   Force finishing activity io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity
01-14 10:51:45.106 I/ActivityManager(1286): Showing crash dialog for package io.github.lonamiwebs.stringlate u0
01-14 10:51:45.596 W/ActivityManager(1286): Activity pause timeout for ActivityRecord{8cabc5d u0 io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity t1572 f}
01-14 10:51:46.113 I/ActivityManager(1286): Killing 27502:io.github.lonamiwebs.stringlate/u0a195 (adj 0): crash
01-14 10:51:46.170 I/ActivityManager(1286): Start proc 29326:io.github.lonamiwebs.stringlate/u0a195 for activity io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity
01-14 10:51:46.185 I/WindowManager(1286): WIN DEATH: Window{70a11e u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity}
01-14 10:51:46.188 I/WindowManager(1286): WIN DEATH: Window{3359f7c u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity}
01-14 10:51:46.211 D/SurfaceFlinger(841): duplicate layer name: changing Splash Screen io.github.lonamiwebs.stringlate to Splash Screen io.github.lonamiwebs.stringlate#1
01-14 10:52:24.651 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:52:24.802 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity: +132ms
01-14 10:52:27.531 I/zygote64(29326): Deoptimizing io.github.lonamiwebs.stringlate.classes.resources.tags.ResTag io.github.lonamiwebs.stringlate.classes.resources.Resources.getTag(java.lang.String) due to JIT inline cache
01-14 10:52:29.756 D/SurfaceFlinger(841): duplicate layer name: changing io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity to io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity#1
01-14 10:52:29.869 W/WindowManager(1286): Attempted to set replacing window on non-existing app token Token{c5e90fb ActivityRecord{c40428a u0 io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity t1572}}
01-14 10:52:45.806 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:52:45.932 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +99ms
01-14 10:52:47.698 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 1 line
01-14 10:53:00.254 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:53:00.379 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +109ms
01-14 10:53:01.713 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 2 lines
01-14 10:53:16.401 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:53:16.510 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +91ms
01-14 10:53:28.711 D/SurfaceFlinger(841): duplicate layer name: changing io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity to io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity#1
01-14 10:53:29.031 W/WindowManager(1286): Attempted to set replacing window on non-existing app token Token{bfdb2ce ActivityRecord{5904bc9 u0 io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity t1572}}
01-14 10:53:31.518 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:53:31.643 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity: +109ms (total +1m2s22ms)
01-14 10:53:32.143 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:53:32.227 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 6 lines
01-14 10:53:32.251 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +91ms
01-14 10:53:44.297 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:53:44.423 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +95ms
01-14 10:53:45.731 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 4 lines
01-14 10:53:45.921 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 5 lines
01-14 10:53:50.757 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity (has extras)} from uid 10195
01-14 10:53:50.863 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.SearchStringActivity: +84ms
01-14 10:53:53.508 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 1 line
01-14 10:53:55.150 I/chatty  (29326): uid=10195(io.github.lonamiwebs.stringlate) identical 1 line
01-14 10:54:41.290 I/ActivityManager(1286): START u0 {cmp=io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity (has extras)} from uid 10195
01-14 10:54:41.418 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity: +107ms
01-14 10:54:45.986 E/AndroidRuntime(29326): Process: io.github.lonamiwebs.stringlate, PID: 29326
01-14 10:54:45.986 E/AndroidRuntime(29326): java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.writeReplaceStrings(ResourcesParser.java:584)
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.applyTemplate(ResourcesParser.java:646)
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.applyTemplate(RepoHandler.java:428)
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.mergeDefaultTemplate(RepoHandler.java:441)
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.exportToCopy(TranslateActivity.java:685)
01-14 10:54:45.986 E/AndroidRuntime(29326): 	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.onOptionsItemSelected(TranslateActivity.java:321)
01-14 10:54:45.989 W/ActivityManager(1286):   Force finishing activity io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity
01-14 10:54:45.999 I/ActivityManager(1286): Showing crash dialog for package io.github.lonamiwebs.stringlate u0
01-14 10:54:46.493 W/ActivityManager(1286): Activity pause timeout for ActivityRecord{5d984f1 u0 io.github.lonamiwebs.stringlate/.activities.translate.TranslateActivity t1572 f}
01-14 10:54:47.477 I/ActivityManager(1286): Killing 29326:io.github.lonamiwebs.stringlate/u0a195 (adj 0): crash
01-14 10:54:47.502 W/InputDispatcher(1286): channel '6740c62 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-14 10:54:47.502 E/InputDispatcher(1286): channel '6740c62 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-14 10:54:47.502 W/InputDispatcher(1286): channel '6c4aea9 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-14 10:54:47.502 E/InputDispatcher(1286): channel '6c4aea9 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-14 10:54:47.521 I/WindowManager(1286): WIN DEATH: Window{6c4aea9 u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity}
01-14 10:54:47.521 W/InputDispatcher(1286): Attempted to unregister already unregistered input channel '6c4aea9 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.repositories.RepositoriesActivity (server)'
01-14 10:54:47.526 I/WindowManager(1286): WIN DEATH: Window{6740c62 u0 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity}
01-14 10:54:47.526 W/InputDispatcher(1286): Attempted to unregister already unregistered input channel '6740c62 io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity (server)'
01-14 10:54:47.534 I/ActivityManager(1286): Start proc 29710:io.github.lonamiwebs.stringlate/u0a195 for activity io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity
01-14 10:54:47.580 D/SurfaceFlinger(841): duplicate layer name: changing Splash Screen io.github.lonamiwebs.stringlate to Splash Screen io.github.lonamiwebs.stringlate#1
01-14 10:54:47.827 I/ActivityManager(1286): Displayed io.github.lonamiwebs.stringlate/.activities.repositories.RepositoriesActivity: +307ms
```

Filtered for Stringlate, hope it helps.

**Comment by gsantner** [comment] 2018-01-14 09:09
@Lonami classcastexception restag - resarray

**Comment by Lonami** [comment] 2018-01-14 09:39
What's the faulty project you're trying to translate? It's like a single item string was loaded, but expected an array, and when saving that it fails.

**Comment by Madis0** [comment] 2018-01-14 09:40
https://github.com/topjohnwu/MagiskManager

**Comment by gsantner** [comment] 2018-03-16 11:24
Closing/merging to #184 , comment over there

**Closed by gsantner** 2018-03-16 11:24 UTC
