### ISSUE TITLE
Does not respect device's screen orientation

### ISSUE THREAD

**Issue by SkyWheel** [LonamiWebs/Stringlate#90] opened 2017-02-21 08:03 UTC
Hi
When I'm trying to rotate screen inside the app it's doing nothing.
Expected: it will rotate the screen according to device settings.
Thank you.

**Comment by SkyWheel** [comment] 2017-02-21 08:17
Just found the commit to lock the rotation #https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd
On my device it's a pain: I get used to use in different rotations. Usually I use ALL 4 rotations...
Could you please add manual option to enable/disable rotations?
I think it will be comfortable for everybody.
Thank you.

**Comment by XyLoNaMiyX** [comment] 2017-02-21 08:31
The problem is that this would break #26, #27, #28, #29 and #30 :)

I know that it would be nice if I could provide a different layout for landscape (on tablets, the search could be on the left while the right for the translations). But quite a few changes are probably required and not easy (see _rewriting all the activities to use fragments instead_, and not even then I'm sure if it will be easy).

But yes, this is definitely an issue. If anyone is willing to close this I'll happily merge :P

**Comment by SkyWheel** [comment] 2017-02-21 09:04
@XyLoNaMiyX 
/sigh/ Unfortunately, I'm not a coder at all. Otherwise I would be happy to help in issue resolving...
Could you please link this issue as a conflict with pr #https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd?

**Comment by XyLoNaMiyX** [comment] 2017-02-21 10:32
> Could you please link this issue as a conflict with pr #6407067?

Not sure what you meant. As far as I know, there's no such thing as "linking" issues with commits? Keeping it on the comments here (as you did) should be enough :)

**Comment by Lonami** [comment] 2017-08-22 14:18
https://github.com/LonamiWebs/Stringlate/commit/4b5a50a85e881163eb40fa7086ff21cc4f7aa492 is the first step:
> **Create a nicer RepoSyncTask and get rid of two ProgressDialogs**
> ```
> This actually lifts the limitation that forced portrait mode
> to avoid certain crashes, like issue #28. Work still needs to
> be done for issues 26, 27, 29 and 30 to get rotation working.
> ```

**Comment by Lonami** [comment] 2017-10-02 11:33
I forgot this should work as of [`v0.10`](https://github.com/LonamiWebs/Stringlate/releases/tag/v0.10). Closing issue.

**Closed by Lonami** 2017-10-02 11:33 UTC
